services:
  redis:
    image: redis:7-alpine

  airflow-init:
    build:
      context: ./airflow
    image: mrp-airflow:3.1.6-custom
    user: "${AIRFLOW_UID:-50000}:0"
    depends_on:
      - postgres
      - redis
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://app:app@postgres:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://app:app@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      AIRFLOW__CORE__FERNET_KEY: "wY-3nxR1Ty-y6rFBgVQRVuF7hdce-FYTxeYg0WRPnLo="
      AIRFLOW__API_AUTH__JWT_SECRET: "lS7A2mK-03QwrWBORlsf6Ywb029O9WvvC-ZtgUDT_Sg="
      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: "http://airflow-apiserver:8080/execution/"
      AIRFLOW_CONN_MRP_POSTGRES: postgresql://app:app@postgres:5432/appdb
      AIRFLOW_CONN_MRP_INGESTION_API: http://ingestion-api:8000
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    entrypoint: /bin/bash
    command: -lc "airflow db migrate && airflow users create --username airflow --password airflow --firstname Airflow --lastname Admin --role Admin --email airflow@example.com || true"

  airflow-apiserver:
    image: mrp-airflow:3.1.6-custom
    user: "${AIRFLOW_UID:-50000}:0"
    depends_on:
      - postgres
      - redis
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://app:app@postgres:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://app:app@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      AIRFLOW__CORE__FERNET_KEY: "wY-3nxR1Ty-y6rFBgVQRVuF7hdce-FYTxeYg0WRPnLo="
      AIRFLOW__API_AUTH__JWT_SECRET: "lS7A2mK-03QwrWBORlsf6Ywb029O9WvvC-ZtgUDT_Sg="
      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: "http://airflow-apiserver:8080/execution/"
      AIRFLOW_CONN_MRP_POSTGRES: postgresql://app:app@postgres:5432/appdb
      AIRFLOW_CONN_MRP_INGESTION_API: http://ingestion-api:8000
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: api-server

  airflow-scheduler:
    image: mrp-airflow:3.1.6-custom
    user: "${AIRFLOW_UID:-50000}:0"
    depends_on:
      - postgres
      - redis
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://app:app@postgres:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://app:app@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      AIRFLOW__CORE__FERNET_KEY: "wY-3nxR1Ty-y6rFBgVQRVuF7hdce-FYTxeYg0WRPnLo="
      AIRFLOW__API_AUTH__JWT_SECRET: "lS7A2mK-03QwrWBORlsf6Ywb029O9WvvC-ZtgUDT_Sg="
      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: "http://airflow-apiserver:8080/execution/"
      AIRFLOW_CONN_MRP_POSTGRES: postgresql://app:app@postgres:5432/appdb
      AIRFLOW_CONN_MRP_INGESTION_API: http://ingestion-api:8000
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    command: scheduler

  airflow-dag-processor:
    image: mrp-airflow:3.1.6-custom
    user: "${AIRFLOW_UID:-50000}:0"
    depends_on:
      - postgres
      - redis
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://app:app@postgres:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://app:app@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      AIRFLOW__CORE__FERNET_KEY: "wY-3nxR1Ty-y6rFBgVQRVuF7hdce-FYTxeYg0WRPnLo="
      AIRFLOW__API_AUTH__JWT_SECRET: "lS7A2mK-03QwrWBORlsf6Ywb029O9WvvC-ZtgUDT_Sg="
      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: "http://airflow-apiserver:8080/execution/"
      AIRFLOW_CONN_MRP_POSTGRES: postgresql://app:app@postgres:5432/appdb
      AIRFLOW_CONN_MRP_INGESTION_API: http://ingestion-api:8000
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    command: dag-processor

  airflow-triggerer:
    image: mrp-airflow:3.1.6-custom
    user: "${AIRFLOW_UID:-50000}:0"
    depends_on:
      - postgres
      - redis
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://app:app@postgres:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://app:app@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      AIRFLOW__CORE__FERNET_KEY: "wY-3nxR1Ty-y6rFBgVQRVuF7hdce-FYTxeYg0WRPnLo="
      AIRFLOW__API_AUTH__JWT_SECRET: "lS7A2mK-03QwrWBORlsf6Ywb029O9WvvC-ZtgUDT_Sg="
      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: "http://airflow-apiserver:8080/execution/"
      AIRFLOW_CONN_MRP_POSTGRES: postgresql://app:app@postgres:5432/appdb
      AIRFLOW_CONN_MRP_INGESTION_API: http://ingestion-api:8000
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    command: triggerer

  airflow-worker:
    image: mrp-airflow:3.1.6-custom
    user: "${AIRFLOW_UID:-50000}:0"
    depends_on:
      - postgres
      - redis
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://app:app@postgres:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://app:app@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      AIRFLOW__CORE__FERNET_KEY: "wY-3nxR1Ty-y6rFBgVQRVuF7hdce-FYTxeYg0WRPnLo="
      AIRFLOW__API_AUTH__JWT_SECRET: "lS7A2mK-03QwrWBORlsf6Ywb029O9WvvC-ZtgUDT_Sg="
      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: "http://airflow-apiserver:8080/execution/"
      AIRFLOW_CONN_MRP_POSTGRES: postgresql://app:app@postgres:5432/appdb
      AIRFLOW_CONN_MRP_INGESTION_API: http://ingestion-api:8000
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    command: celery worker
